@echo off
title clean8

del /s /q ""C:\Users\%Username%\AppData\Local\VirtualStore"" do rmdir ""%%p""
RD /s /q ""C:\Users\%Username%\AppData\Local\UnrealEngineLauncher""
RD /s /q ""C:\Users\%Username%\AppData\Local\UnrealEngine""
RD /s /q ""C:\Users\%Username%\AppData\Local\Speech Graphics""
RD /s /q ""C:\Users\%Username%\AppData\Local\Publishers""
RD /s /q ""C:\Users\%Username%\AppData\Local\Programs\Common""
RD /s /q ""C:\Users\%Username%\AppData\Local\PlaceholderTileLogoFolder""
RD /s /q ""C:\Users\%Username%\AppData\Roaming\EasyAntiCheat""
del /f /s /q ""C:\Users\Public\Libraries\*.*""
rmdir /s /q ""C:\Users\Public\Libraries""
del /f /s /q ""C:\Users\%username%\AppData\Local\Microsoft\Feeds\*.*""
rmdir /s /q ""C:\Users\%username%\AppData\Local\Microsoft\Feeds""
del /f /s /q ""C:\MSOCache\*.*""
rmdir /s /q ""C:\MSOCache""
del /f /s /q ""C:\Intel\*.*""
rmdir /s /q ""C:\Intel""
del /f /s /q ""C:\Recovery\*.*""
rmdir /s /q ""C:\Recovery""
del /q /s ""D:\desktop.ini""
del /q /s ""C:\Users\%username%\AppData\Local\Microsoft\Feeds""
del /a /q /s ""C:\Users\%Username%\AppData\Local\updater.log""
del ""%localappdata%\Microsoft\Feeds"" /s /f /q
@RD /S /Q ""%C:\MSOCache\{71230000-00E2-0000-1000-00000000}""
del /s /f /q %userprofile%\Recent\*.*
del /s /f /q C:\Windows\Prefetch\*.*
del /s /f /q C:\Windows\Temp\*.*
del /s /f /q C:\Windows\Public\Libraries\*.*
del /s /f /q %windir%\temp\*.*
del /s /f /q %windir%\Prefetch\*.*
rd /s /q %windir%\Prefetch
rmdir /s /q ""%systemdrive%\Windows\System32\wbem\Repository\MAPPING3.MAP\*.*""
del %windir%\KB*.log /f /q
del /f /s /q %systemdrive%\*.log
del /f /s /q %systemdrive%\*.tmp
del /f /s /q %systemdrive%\*.chk
del /f /s /q %systemdrive%\*.dlf
del /f /s /q %systemdrive%\*.old
del /f /s /q %windir%\*.bak
del /f /s /q %windir%\prefetch\*.*
del /f /s /q %systemdrive%\recycled\*.*
del /f /s /q %windir%\*.bak
del /f /s /q ""%Temp%""
rd /s /q %windir%\temp md %windir%\temp
del /f /s /q ""%systemdrive%\ProgramData\Origin\AchievementCache\*""
del /f /s /q ""%systemdrive%\ProgramData\Origin\CatalogCache\*""
del /f /s /q ""%systemdrive%\ProgramData\Origin\CustomBoxartCache\*""
del /f /s /q ""%systemdrive%\ProgramData\Origin\EntitlementCache\*""
del /f /s /q ""%systemdrive%\ProgramData\Origin\IGOCache\*""
del /f /s /q ""%systemdrive%\ProgramData\Origin\Logs\*""
del /f /s /q ""%systemdrive%\ProgramData\Origin\NonOriginContentCache\*""
del /f /s /q ""%systemdrive%\ProgramData\Origin\Subscription\*""
del /f /s /q ""%systemdrive%\ProgramData\Origin\Telemetry\*""
del /f /s /q ""%systemdrive%\ProgramData\Origin\*""
del /f /s /q ""%systemdrive%\ProgramData\Electronic Arts\EA Services\License\*""
del /f /s /q ""%systemdrive%\ProgramData\Electronic Arts\*""
del /s /f /a:h /a:a /q  ""%systemdrive%\ProgramData\Origin\AchievementCache\*""
del /s /f /a:h /a:a /q  ""%systemdrive%\ProgramData\Origin\CatalogCache\*""
del /s /f /a:h /a:a /q  ""%systemdrive%\ProgramData\Origin\CustomBoxartCache\*""
del /s /f /a:h /a:a /q  ""%systemdrive%\ProgramData\Origin\EntitlementCache\*""
del /s /f /a:h /a:a /q  ""%systemdrive%\ProgramData\Origin\IGOCache\*""
del /s /f /a:h /a:a /q  ""%systemdrive%\ProgramData\Origin\Logs\*""
del /s /f /a:h /a:a /q  ""%systemdrive%\ProgramData\Origin\NonOriginContentCache\*""
del /s /f /a:h /a:a /q  ""%systemdrive%\ProgramData\Origin\Subscription\*""
del /s /f /a:h /a:a /q  ""%systemdrive%\ProgramData\Origin\Telemetry\*""
del /s /f /a:h /a:a /q  ""%systemdrive%\ProgramData\Origin\*""
del /s /f /a:h /a:a /q ""%systemdrive%\ProgramData\Electronic Arts\EA Services\License\*""
del /s /f /a:h /a:a /q ""%systemdrive%\ProgramData\Electronic Arts\*""
del /f /s /q ""x:\$RECYCLE.BIN""
del /f /s /q ""x:\PerfLogs""
del /f /s /q ""x:\MSOCache""
del /f /s /q ""x:\Recovery\ntuser.sys""
del /f /s /q ""x:\System Volume Information""
del /f /s /q ""yourUSB\System Volume Information""
del /f /s /q ""x:\Users\Public\Libraries\collection.dat""
del /f /s /q ""x:\Users\Default\NTUSER.DAT""
del /f /s /q ""x:\Users\yourname\ntuser.ini""
del /f /s /q ""x:\Users\Public\Shared Files""
del /f /s /q ""x:\Users\Public\Libraries""
del /f /s /q ""x:\ProgramData\ntuser.pol""
del /f /s /q ""x:\localappdata\Microsoft\INetCache""
del /f /s /q ""x:\%programdata%\Origin -> delete everything expect ""LocalContent"" folder
del /f /s /q ""x:\%localappdata%\Origin""
del /f /s /q ""x:\%appdata%\Origin""
del /f /s /q ""x:\%homepath%\.Origin""
del /f /s /q ""x:\%homepath%\.QtWebEngineProcess""
del /f /s /q ""x:\%programdata%\Electronic Arts""
del /f /s /q ""x:\%programfiles%\Common Files\EAInstaller""
del /s /f /a:h /a:a /q  ""x:\%programdata%\Origin""
del /s /f /a:h /a:a /q  ""x:\%localappdata%\Origin""
del /s /f /a:h /a:a /q  ""x:\%appdata%\Origin""
del /s /f /a:h /a:a /q  ""x:\%homepath%\.Origin""
del /s /f /a:h /a:a /q  ""x:\%homepath%\.QtWebEngineProcess""
del /s /f /a:h /a:a /q  ""x:\%programdata%\Electronic Arts""
del /s /f /a:h /a:a /q  ""x:\%programfiles%\Common Files\EAInstaller""
del /s /f /a:h /a:a /q  ""%systemdrive%\ProgramData\Origin""
del /f /s /q ""x:\%programdata%\Microsoft\Windows\Start Menu\Programs\Origin""
del /f /s /q ""x:\%systemdrive%\ProgramData\Microsoft\Windows\Start Menu\Programs\Apex Legends""
del /f /s /q ""x:\%systemdrive%\Windows\ServiceProfiles\LocalService\AppData\Local\Origin""
del /f /s /q ""x:\%systemdrive%\Windows\ServiceProfiles\LocalService\AppData\Roaming\Origin""
del /f /s /q ""x:\%localappdata%\NVIDIA\NvBackend\ApplicationOntology\data\wrappers\apex_legends""
del /f /s /q ""x:\%appdata%\EasyAntiCheat""
del /f /s /q ""x:\%localappdata%\Temp""
del /f /s /q ""x:\%localappdata%\ConnectedDevicesPlatform""
del /s /f /a:h /a:a /q ""%systemdrive%\Users\%username%\AppData\Roaming\Microsoft\Crypto\RSA\*""
del /s /f /a:h /a:a /q ""%systemdrive%\Users\%username%\AppData\Roaming\Microsoft\Crypto\Keys\*""
del /s /f /a:h /a:a /q ""%systemdrive%\Users\%username%\AppData\Roaming\Microsoft\SystemCertificates\My\Certificates\*""
del /s /f /a:h /a:a /q ""%systemdrive%\Users\%username%\AppData\Roaming\Microsoft\SystemCertificates\My\Keys\*""
del /s /f /a:h /a:a /q ""%systemdrive%\Users\%username%\AppData\Local\UnrealEngine\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Users\Public\Libraries\collection.dat\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\MSOCache\{71230000-00E2-0000-1000-00000000}\Setup.dat\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Users\%username%\AppData\Local\Microsoft\Windows\WebCache\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Users\%username%\AppData\Local\Microsoft\Feeds\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\ProgramData\Microsoft\DataMart\PaidWiFi\NetworksCache\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\ProgramData\Microsoft\DataMart\PaidWiFi\Rules\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Users\%username%\AppData\Local\Microsoft\Windows\History\History.IE5\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Users\%username%\AppData\Local\Speech Graphics\Carnival\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\ProgramData\Microsoft\Windows\WER\Temp\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Windows\SysWOW64\config\systemprofile\AppData\Local\Microsoft\Windows\INetCache\Content.IE5\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Windows\SysWOW64\config\systemprofile\AppData\Local\Microsoft\Windows\INetCookies\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Windows\SysWOW64\config\systemprofile\AppData\LocalLow\Microsoft\CryptnetUrlCache\MetaData\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Windows\SysWOW64\config\systemprofile\AppData\LocalLow\Microsoft\CryptnetUrlCache\Content\*.*""
del /f /s /q ""%systemdrive%\Users\%username%\AppData\Local\UnrealEngine\*.*""
del /f /s /q ""%systemdrive%\Program Files (x86)\EasyAntiCheat\EasyAntiCheat.sys""
del /f /s /q ""%systemdrive%\ProgramData\Electronic Arts\EA Services\License\*.*""
del /f /s /q ""%systemdrive%\ProgramData\Origin\*.*""
del /f /s /q ""%systemdrive%\Users\%username%\AppData\Local\Origin\*.*""
del /f /s /q ""%systemdrive%\Users\%username%\AppData\Roaming\Origin\*.*""
del /f /s /q ""%systemdrive%\Users\%username%\AppData\Roaming\EasyAntiCheat\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Users\%username%\AppData\Local\UnrealEngine\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Program Files (x86)\EasyAntiCheat\EasyAntiCheat.sys""
del /s /f /a:h /a:a /q ""%systemdrive%\ProgramData\Electronic Arts\EA Services\License\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\ProgramData\Origin\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Users\%username%\AppData\Local\Origin\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Users\%username%\AppData\Roaming\Origin\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Users\%username%\AppData\Roaming\EasyAntiCheat\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\ProgramData\Electronic Arts\EA Services\License""
del /s /f /a:h /a:a /q ""%systemdrive%\ProgramData\Origin""
del /s /f /a:h /a:a /q ""%systemdrive%\Users\%username%\AppData\Local\Origin""
del /s /f /a:h /a:a /q ""%systemdrive%\Users\%username%\AppData\Roaming\Origin""
del /s /f /a:h /a:a /q ""%systemdrive%\Users\%username%\AppData\Roaming\EasyAntiCheat""
del /f /s /q ""%systemdrive%\Users\%username%\Saved Games\Respawn\Apex\local\previousgamestate.txt""
del /f /s /q ""%systemdrive%\Users\Public\Libraries\collection.dat\*.*""
del /f /s /q ""%systemdrive%\MSOCache\{71230000-00E2-0000-1000-00000000}\Setup.dat\*.*""
del /f /s /q ""%systemdrive%\Users\%username%\AppData\Local\Microsoft\Windows\WebCache\*.*""
del /f /s /q ""%systemdrive%\Users\%username%\AppData\Local\Microsoft\Feeds\*.*""
del /f /s /q ""%systemdrive%\ProgramData\Microsoft\DataMart\PaidWiFi\NetworksCache\*.*""
del /f /s /q ""%systemdrive%\ProgramData\Microsoft\DataMart\PaidWiFi\Rules\*.*""
del /f /s /q ""%systemdrive%\Users\%username%\AppData\Local\Microsoft\Windows\History\History.IE5\*.*""
del /f /s /q ""%systemdrive%\Users\%username%\AppData\Local\Speech Graphics\Carnival\*.*""
del /f /s /q ""%systemdrive%\ProgramData\Microsoft\Windows\WER\Temp\*.*""
del /f /s /q ""%systemdrive%\Windows\SysWOW64\config\systemprofile\AppData\Local\Microsoft\Windows\INetCache\Content.IE5\*.*""
del /f /s /q ""%systemdrive%\Windows\SysWOW64\config\systemprofile\AppData\Local\Microsoft\Windows\INetCookies\*.*""
del /f /s /q ""%systemdrive%\Windows\SysWOW64\config\systemprofile\AppData\Local\Origin\*.*
del /f /s /q ""%systemdrive%\Windows\SysWOW64\config\systemprofile\AppData\LocalLow\Origin\*.*
del /f /s /q ""%systemdrive%\Windows\SysWOW64\config\systemprofile\AppData\Roaming\Origin\*.*
del /f /s /q ""%systemdrive%\Windows\SysWOW64\config\systemprofile\AppData\LocalLow\Microsoft\CryptnetUrlCache\MetaData\*.*""
del /f /s /q ""%systemdrive%\Windows\SysWOW64\config\systemprofile\AppData\LocalLow\Microsoft\CryptnetUrlCache\Content\*.*""
del /s /f /q ""%systemdrive%\Windows\Public\Libraries\*.*""
del /s /f /q ""%systemdrive%\Windows\Prefetch\*.*""
del /f /s /q ""%systemdrive%\Intel\*.*""
del /f /s /q ""%systemdrive%\desktop.ini\*.*""
del /f /s /q ""%systemdrive%paint\Users\%username%\AppData\Roaming\vstelemetry\*.*""
del /f /s /q ""%windir%\prefetch\*.*""
del /f /q ""%userprofile%\recent\*.*""
del /f /s /q ""%userprofile%\Local Settings\Temporary Internet Files\*.*""
del /f /s /q ""%userprofile%\Local Settings\Temp\*.*""
del /f /s /q ""%userprofile%\recent\*.*""
del /f /s /q ""%Temp%""
del /f /s /q ""%systemdrive%\ProgramData\Origin\AchievementCache\*""
del /f /s /q ""%systemdrive%\ProgramData\Origin\CatalogCache\*""
del /f /s /q ""%systemdrive%\ProgramData\Origin\CustomBoxartCache\*""
del /f /s /q ""%systemdrive%\ProgramData\Origin\EntitlementCache\*""
del /f /s /q ""%systemdrive%\ProgramData\Origin\IGOCache\*""
del /f /s /q ""%systemdrive%\ProgramData\Origin\Logs\*""
del /f /s /q ""%systemdrive%\ProgramData\Origin\NonOriginContentCache\*""
del /f /s /q ""%systemdrive%\ProgramData\Origin\Subscription\*""
del /f /s /q ""%systemdrive%\ProgramData\Origin\Telemetry\*""
rd /s /q ""%systemdrive%\ProgramData\Origin""
del /s /f /a:h /a:a /q ""%systemdrive%\ProgramData\Origin\AchievementCache\*""
del /s /f /a:h /a:a /q ""%systemdrive%\ProgramData\Origin\CatalogCache\*""
del /s /f /a:h /a:a /q ""%systemdrive%\ProgramData\Origin\CustomBoxartCache\*""
del /s /f /a:h /a:a /q ""%systemdrive%\ProgramData\Origin\EntitlementCache\*""
del /s /f /a:h /a:a /q ""%systemdrive%\ProgramData\Origin\IGOCache\*""
del /s /f /a:h /a:a /q ""%systemdrive%\ProgramData\Origin\Logs\*""
del /s /f /a:h /a:a /q ""%systemdrive%\ProgramData\Origin\NonOriginContentCache\*""
del /s /f /a:h /a:a /q ""%systemdrive%\ProgramData\Origin\Subscription\*""
del /s /f /a:h /a:a /q ""%systemdrive%\ProgramData\Origin\Telemetry\*""
rd /s /a:h /a:a /q ""%systemdrive%\ProgramData\Origin""
rd /q /s %systemdrive%\$Recycle.Bin
rd /q /s A:\$Recycle.Bin
rd /q /s B:\$Recycle.Bin
rd /q /s C:\$Recycle.Bin
rd /q /s D:\$Recycle.Bin
rd /q /s E:\$Recycle.Bin
rd /q /s F:\$Recycle.Bin
rd /q /s G:\$Recycle.Bin
rd /q /s H:\$Recycle.Bin
rd /q /s I:\$Recycle.Bin
rd /q /s J:\$Recycle.Bin
rd /q /s K:\$Recycle.Bin
rd /q /s L:\$Recycle.Bin
rd /q /s M:\$Recycle.Bin
rd /q /s N:\$Recycle.Bin
rd /q /s O:\$Recycle.Bin
rd /q /s P:\$Recycle.Bin
rd /q /s Q:\$Recycle.Bin
rd /q /s R:\$Recycle.Bin
rd /q /s S:\$Recycle.Bin
rd /q /s T:\$Recycle.Bin
rd /q /s U:\$Recycle.Bin
rd /q /s V:\$Recycle.Bin
rd /q /s W:\$Recycle.Bin
rd /q /s X:\$Recycle.Bin
rd /q /s Y:\$Recycle.Bin
rd /q /s Z:\$Recycle.Bin
del /f /s /q ""x:\$RECYCLE.BIN""
del /f /s /q ""x:\PerfLogs""
del /f /s /q ""x:\MSOCache""
del /f /s /q ""x:\Users\Public\Shared Files""
del /f /s /q ""x:\Users\Public\Libraries""
del /f /s /q ""x:\localappdata\Microsoft\INetCache""
del /f /s /q ""x:\%localappdata%\Origin""
del /f /s /q ""x:\%appdata%\Origin""
del /f /s /q ""x:\%homepath%\.Origin""
del /f /s /q ""x:\%homepath%\.QtWebEngineProcess""
del /f /s /q ""x:\%programdata%\Electronic Arts""
del /f /s /q ""x:\%programfiles%\Common Files\EAInstaller""
del /f /s /q ""x:\%programdata%\Microsoft\Windows\Start Menu\Programs\Origin""
del /f /s /q ""x:\%systemdrive%\ProgramData\Microsoft\Windows\Start Menu\Programs\Apex Legends""
del /f /s /q ""x:\%systemdrive%\Windows\ServiceProfiles\LocalService\AppData\Local\Origin""
del /f /s /q ""x:\%systemdrive%\Windows\ServiceProfiles\LocalService\AppData\Roaming\Origin""
del /f /s /q ""x:\%localappdata%\NVIDIA\NvBackend\ApplicationOntology\data\wrappers\apex_legends""
del /f /s /q ""x:\%appdata%\EasyAntiCheat""
del /f /s /q ""x:\%localappdata%\Temp""
del /f /s /q ""x:\%localappdata%\ConnectedDevicesPlatform""
del /f /s /q ""%systemdrive%\MSOCache\{71230000-00E2-0000-1000-00000000}\Setup.dat\*.*""
del /f /s /q ""%systemdrive%\Users\%username%\AppData\Local\Microsoft\Windows\WebCache\*.*""
del /f /s /q ""%systemdrive%\Users\%username%\AppData\Local\Microsoft\Feeds\*.*""
del /f /s /q ""%systemdrive%\ProgramData\Microsoft\DataMart\PaidWiFi\NetworksCache\*.*""
del /f /s /q ""%systemdrive%\ProgramData\Microsoft\DataMart\PaidWiFi\Rules\*.*""
del /f /s /q ""%systemdrive%\Users\%username%\AppData\Local\Microsoft\Windows\History\History.IE5\*.*""
del /f /s /q ""%systemdrive%\Users\%username%\AppData\Local\Speech Graphics\Carnival\*.*""
del /f /s /q ""%systemdrive%\ProgramData\Microsoft\Windows\WER\Temp\*.*""
del /f /s /q ""%systemdrive%\Windows\SysWOW64\config\systemprofile\AppData\Local\Microsoft\Windows\INetCache\Content.IE5\*.*""
del /f /s /q ""%systemdrive%\Windows\SysWOW64\config\systemprofile\AppData\Local\Microsoft\Windows\INetCookies\*.*""
del /f /s /q ""%systemdrive%\Windows\SysWOW64\config\systemprofile\AppData\LocalLow\Microsoft\CryptnetUrlCache\MetaData\*.*""
del /f /s /q ""%systemdrive%\Windows\SysWOW64\config\systemprofile\AppData\LocalLow\Microsoft\CryptnetUrlCache\Content\*.*""
del /s /f /q ""%systemdrive%\Windows\Prefetch\*.*""
del /f /s /q ""%systemdrive%\Intel\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Users\%username%\AppData\Roaming\Microsoft\Windows\Themes\CachedFiles\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Windows\SysWOW64\config\systemprofile\AppData\Local\Microsoft\Windows\INetCache\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Windows\System32\config\systemprofile\AppData\Local\Microsoft\Windows\WebCache\WebCacheV01.dat\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Windows\System32\config\systemprofile\AppData\Local\Microsoft\Windows\WebCache\WebCacheV01.jfm\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Users\%username%\AppData\LocalLow\Microsoft\CryptnetUrlCache\MetaData\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Users\%username%\AppData\Local\Microsoft\Windows\INetCache\IE\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Windows\Prefetch\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Users\%username%\AppData\Roaming\Microsoft\Windows\Recent\AutomaticDestinations\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\ProgramData\Microsoft\Windows\DeviceMetadataCache\dmrc.idx\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Users\%username%\AppData\Local\Microsoft\Windows\WebCache\WebCacheV01.dat\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\ProgramData\Microsoft\Windows\DeviceMetadataCache\dmrc.idx\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Users\%username%\AppData\Local\Microsoft\Internet Explorer\CacheStorage\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Users\%username%\AppData\Local\AMD\DxCache\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Program Files (x86)\AMD\CNext\CCCSlim\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Users\%username%\AppData\Local\PlaceholderTileLogoFolder\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Users\%username%\AppData\LocalLow\Microsoft\CryptnetUrlCache\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Users\%username%\AppData\Local\Microsoft\Windows\WebCache\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Users\%username%\AppData\Roaming\Microsoft\Windows\Themes\CachedFiles\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Windows\ServiceProfiles\LocalService\AppData\Local\FontCache\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Users\%username%\AppData\Roaming\Microsoft\Windows\CloudStore\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Windows\Prefetch\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\ProgramData\Microsoft\Diagnosis\EventStore.db-wal\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Windows\System32\perfc009.dat\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Windows\System32\perfh009.dat\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Windows\INF\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Windows\System32\PerfStringBackup.TMP\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Windows\System32\PerfStringBackup.INI\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Users\%username%\ntuser.dat.LOG2\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Windows\System32\wbem\Performance\WmiApRpl.ini\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Windows\TEMP\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Windows\SoftwareDistribution\DataStore\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Windows\System32\WDI\LogFiles\StartupInfo\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Windows\ServiceProfiles\NetworkService\AppData\Local\Microsoft\Windows\DeliveryOptimization\Logs\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Windows\ServiceProfiles\NetworkService\AppData\Local\Microsoft\Windows\DeliveryOptimization\State\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Windows\SysWOW64\Gms.log\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\ProgramData\USOShared\Logs\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Users\%username%\AppData\Local\Microsoft\Windows\SettingSync\remotemetastore\v1\edb.log\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Users\%username%\AppData\Local\Microsoft\Windows\SettingSync\metastore\edb.log\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Windows\Logs\CBS\CBS.log\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Users\%username%\AppData\Local\Comms\Unistore\data\3\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Users\%username%\AppData\Local\Comms\Unistore\data\temp\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Users\%username%\AppData\Local\Packages\Microsoft.MicrosoftEdge_8wekyb3d8bbwe\AppData\User\Default\Indexed DB\edb.log\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Users\%username%\AppData\Local\Microsoft\Windows\SettingSync\metastore\meta.edb\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Users\%username%\AppData\Roaming\Microsoft\Windows\Recent\AutomaticDestinations\b05132b02959bc64.automaticDestinations-ms\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Windows\appcompat\Programs\Amcache.hve\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Users\%username%\AppData\Roaming\EasyAntiCheat\*.*""
del /s /f /a:h /a:a /q ""%systemdrive%\Windows\System32\LogFiles\WMI\RtBackup\EtwRTGraphicsPerfMonitorSession.etl\*.*""
rmdir /s /q ""%systemdrive%\ProgramData\Microsoft\Windows\WER\Temp""
del /f /s /q ""%systemdrive%\Windows\temp\*.*""
rmdir /s /q ""%systemdrive%\Windows\temp\*""
rmdir /s /q ""%systemdrive%\Windows\Logs""
rmdir /s /q ""%systemdrive%\Windows\SoftwareDistribution\DataStore\Logs""
rmdir /s /q ""%systemdrive%\Users\Public\Libraries\collection.dat""
rmdir /s /q ""%systemdrive%\MSOCache\{71230000-00E2-0000-1000-00000000}\Setup.dat""
rmdir /s /q ""%systemdrive%\Users\%username%\AppData\Local\Microsoft\Windows\WebCache""
rmdir /s /q ""%systemdrive%\Users\%username%\AppData\Local\Microsoft\Feeds""
rmdir /s /q ""%systemdrive%\ProgramData\Microsoft\DataMart\PaidWiFi\NetworksCache""
rmdir /s /q ""%systemdrive%\ProgramData\Microsoft\DataMart\PaidWiFi\Rules""
rmdir /s /q ""%systemdrive%\Users\%username%\AppData\Local\Speech Graphics\Carnival""
rmdir /s /q ""%systemdrive%\ProgramData\Microsoft\Windows\WER\Temp""
rmdir /s /q ""%systemdrive%\Windows\SysWOW64\config\systemprofile\AppData\Local\Microsoft\Windows\INetCache\Content.IE5""
rmdir /s /q ""%systemdrive%\Windows\SysWOW64\config\systemprofile\AppData\Local\Microsoft\Windows\INetCookies""
rmdir /s /q ""%systemdrive%\Windows\SysWOW64\config\systemprofile\AppData\LocalLow\Microsoft\CryptnetUrlCache\MetaData""
rmdir /s /q ""%systemdrive%\Windows\SysWOW64\config\systemprofile\AppData\LocalLow\Microsoft\CryptnetUrlCache\Content""
rmdir /s /q ""%systemdrive%\Windows\Public\Libraries""
rmdir /s /q ""%systemdrive%\Windows\Prefetch""
rmdir /s /q ""%systemdrive%\Intel""
rmdir /s /q ""%systemdrive%\desktop.ini""

pause